name: formflow
description: "A robust, flexible, and user-friendly solution for form submission, approval workflows, and integrated notifications."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI and Icons
  cupertino_icons: ^1.0.2
  
  # State Management
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  
  # Firebase
  firebase_core: ^3.15.2
  cloud_firestore: ^5.6.12
  firebase_auth: ^5.7.0
  cloud_functions: ^5.6.2
  
  # HTTP and API
  http: ^1.1.0
  
  # File handling
  file_picker: ^6.1.1
  
  # Utilities
  uuid: ^4.0.0
  intl: ^0.18.1
  url_launcher: ^6.1.14
  
  # UI Components
  flutter_svg: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
  
  # fonts:
  #   - family: Plus Jakarta Sans
  #     fonts:
  #       - asset: assets/fonts/PlusJakartaSans-Regular.ttf
  #       - asset: assets/fonts/PlusJakartaSans-Medium.ttf
  #         weight: 500
  #       - asset: assets/fonts/PlusJakartaSans-SemiBold.ttf
  #         weight: 600
  #       - asset: assets/fonts/PlusJakartaSans-Bold.ttf
  #         weight: 700
  #   - family: Lexend
  #     fonts:
  #       - asset: assets/fonts/Lexend-Regular.ttf
  #       - asset: assets/fonts/Lexend-Medium.ttf
  #         weight: 500
  #       - asset: assets/fonts/Lexend-Light.ttf
  #         weight: 300
  #   - family: Roboto
  #     fonts:
  #       - asset: assets/fonts/Roboto-Regular.ttf
  #       - asset: assets/fonts/Roboto-Medium.ttf
  #         weight: 500
  
  
